

<h2>Menu</h2>
<div id="sidebar">
    <ul>
        <li>> <a href="#magento">Magento Version</a></li>
        <li>> <a href="#php">PHP Information</a></li>
        <li>> <a href="#mysql">MySQL</a></li>
        <li>> <a href="#web">Web Server</a></li>
        <li>> <a href="#module">Modules</a></li>
        <li>> <a href="#cdn">CDN</a></li>
        <li>> <a href="#cpu">CPU</a></li>
        <li>> <a href="#database">Database</a></li>
        <li>> <a href="#disk">Disk</a></li>
        <li>> <a href="#var">Var</a></li>
        <li>> <a href="#session">Session Storage</a></li>
        <li>> <a href="#backend">Backend Cache</a></li>
        <li>> <a href="#magentoc">Magento Cache</a></li>
        <li>> <a href="#log">Log Rotation</a></li>
    </ul>
    
    <br>
    <div>
    Visit my <a href="http://www.eddiespradley.com/blog/" target="_blank">blog</a> for more speed tips.
    </div>
    <br>
    <div>
        <a href="http://www.eddiespradley.com/" target="_blank">Request</a> a FREE consultation from me.
    </div>
</div>